### ISSUE TITLE
Bug in Google.search()

### ISSUE THREAD

**Issue by wannaphong** [rohithpr/py-web-search#19]
I using python 3.4.3 64 bit in windows 8.

``` python
>>> from pws import Google
>>> print(Google.search(query='hello world', num=5, start=2, country_code="es"))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\py34\lib\encodings\cp874.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 232-234:
 character maps to <undefined>
```

**Comment by rohithpr** [comment]
I updated the package on PyPI. Try upgrading and let me know if you still have the issue. I couldn't reproduce it with the latest version.

**Comment by wannaphong** [comment]
Thank you. This issue has been resolved.
